### ISSUE TITLE
xoroshiftall.py bug

### ISSUE THREAD

**Issue by achan001** [lemire/crackingxoroshiro128plus#2]
I made an error when trying to search for next soln
Last line of xoroshiftall.py :
> s.add( x0 != soln[x0], y0 != soln[y0] )

What I intended were to remove 1 (solved) seed from search space.
But above rule added *simultaneous equations* instead.

-> comma acted like a AND (not OR)
-> possibly remove more than 1 state: (x0, ?) and (?, y0)

To remove just 1 state, I should use **z3.Or**
>s.add( z3.Or(x0 != soln[x0], y0 != soln[y0]) )

The bug is probably not serious enough to give the wrong answer.
But with bigger states, say 256 bits, **z3.Or** is REQUIRED

see my xoshiro256-seed solver: https://github.com/achan001/xoshiro256-seed

**Comment by lemire** [comment]
Great. Hopefully I fixed the issue.

**Comment by achan001** [comment]
As expected, the **bug** will ***not*** give the wrong answer

***Prove:***
Assume 2 valid ***xoroshiro128+*** seed (x0, y0), (x0, y1), y0 != y1

> (x0 + y0) mod 2^64 = output1
> (x0 + y1) mod 2^64 = output1

Subtract the 2 equations, we get: (y0 - y1) mod 2^64 = 0
Since all variables are 64-bits integer, we have y0 = y1

--> remove seed (x0, y0) == remove seed (x0, ?)
--> remove seed (x0, y0) == remove seed (?, y0)
--> the **bug** *luckily* also remove (x0, ?) and (?, y0)

***QED***
